// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, http, querystring;

  express = require("express");

  http = require("http");

  querystring = require('querystring');

  app = express();

  app.use(express["static"](__dirname + "/public"));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.get("/", function(req, res) {
    return res.sendfile(__dirname + "/index.html");
  });

  app.post("/request", function(req, res) {
    var options, request, requestData, timerBegin, url;
    url = require('url').parse(req.body.url);
    requestData = querystring.stringify(req.body.parameters);
    options = {
      host: url.host,
      path: url.path,
      method: req.body.method,
      auth: req.body.auth,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        "Content-Length": requestData.length
      }
    };
    timerBegin = Date.now();
    request = http.request(options, function(response) {
      var body;
      body = '';
      response.on("data", function(chunk) {
        return body += chunk;
      });
      return response.on("end", function() {
        var responseData;
        responseData = {
          status: response.statusCode,
          header: JSON.stringify(response.headers, null, 4),
          body: body,
          time: (Date.now() - timerBegin) / 1000
        };
        return res.send(responseData);
      });
    });
    request.on("error", function(e) {
      return console.log("Error: " + e.message);
    });
    if (req.body.method !== 'GET') {
      request.write(requestData);
    }
    return request.end();
  });

  app.listen(8088);

}).call(this);
